// build.js — renders posts/*.md into /writing/ and modules/ into /uni/.
//
// maths and syntax highlighting are resolved here rather than in the browser,
// so a published post carries no javascript and never flashes raw "$x^2$".
// a post that uses neither also links neither stylesheet.
//
//   node build.js            build posts/ into writing/
//   node build.js --drafts   also build drafts/, for local preview only
//
// the output is a pure function of the sources: writing/ and uni/ are wiped
// and regenerated each run, which is what lets ci detect a stale commit.

import fs from "node:fs";
import path from "node:path";
import MarkdownIt from "markdown-it";
import anchor from "markdown-it-anchor";
import footnote from "markdown-it-footnote";
import container from "markdown-it-container";
import katexPlugin from "@vscode/markdown-it-katex";
import { createHighlighter } from "shiki";
import { parseDeck } from "./anki.js";

const SITE = {
  origin: "https://ashmitrao.com",
  author: "Ashmit Rao",
  handle: "ashmit",
  seg: "writing", // url segment, nav label and shell path all at once
};

const ROOT = import.meta.dirname;
const OUT = path.join(ROOT, SITE.seg);

// each generated page names the sources it came from; the wipe guard below
// looks only for the common prefix, so both trees are covered by one check
const MARKER = (src) => `<!-- generated by build.js — edit the markdown in ${src}/, not this file -->`;
const GENERATED = "<!-- generated by build.js";

const withDrafts = process.argv.includes("--drafts");

/* ---------- helpers ---------- */

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const MONTHS = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"];
// dates are formatted from the iso string, never from a clock, so that a
// rebuild on a different day produces byte-identical output
function human(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  return `${d} ${MONTHS[m - 1]} ${y}`;
}
function rfc822(iso) {
  return new Date(`${iso}T12:00:00Z`).toUTCString();
}

// a deliberately small front-matter subset: "key: value" lines, no nesting
function frontMatter(raw, file) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) throw new Error(`${file}: missing --- front matter block`);
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    if (!line.trim()) continue;
    const at = line.indexOf(":");
    if (at === -1) throw new Error(`${file}: bad front-matter line "${line}"`);
    meta[line.slice(0, at).trim()] = line.slice(at + 1).trim();
  }
  return { meta, body: raw.slice(m[0].length) };
}

/* ---------- markdown ---------- */

const THEOREMS = ["theorem", "lemma", "definition", "proof", "remark"];

const highlighter = await createHighlighter({
  themes: ["vitesse-light", "vitesse-dark"],
  langs: ["lean4", "python", "haskell", "rust", "bash", "javascript", "typescript",
          "json", "html", "css", "sql", "c", "cpp", "latex", "diff", "text"],
});

const md = new MarkdownIt({
  html: true,      // an escape hatch for the odd bit of raw markup
  linkify: true,
  typographer: false, // straight quotes suit a monospace page
  highlight(code, lang) {
    const known = highlighter.getLoadedLanguages().includes(lang);
    // defaultColor:false emits both palettes as css variables, so the theme
    // toggle drives code colour from style.css with no javascript
    return highlighter.codeToHtml(code.replace(/\n$/, ""), {
      lang: known ? lang : "text",
      themes: { light: "vitesse-light", dark: "vitesse-dark" },
      defaultColor: false,
    });
  },
});

md.use(footnote);
md.use(katexPlugin.default ?? katexPlugin);
md.use(anchor, {
  level: [2, 3, 4],
  permalink: anchor.permalink.linkInsideHeader({
    symbol: "#", placement: "after", class: "anchor", ariaHidden: true,
  }),
});
for (const kind of THEOREMS) {
  md.use(container, kind, {
    render(tokens, i) {
      if (tokens[i].nesting !== 1) return "</div>\n";
      const name = tokens[i].info.trim().slice(kind.length).trim();
      const label = name ? `${kind} — ${name}` : kind;
      return `<div class="thm thm--${kind}"><p class="thm-label">${esc(label)}</p>\n`;
    },
  });
}

// the post title already occupies <h2>, so "## foo" in a post becomes <h3>
md.core.ruler.push("demote_headings", (state) => {
  for (const t of state.tokens) {
    if (t.type === "heading_open" || t.type === "heading_close") {
      t.tag = "h" + Math.min(Number(t.tag.slice(1)) + 1, 6);
    }
  }
});

// footnote headings would duplicate the post's own <h2>; drop the rule/label
md.renderer.rules.footnote_block_open = () =>
  '<hr class="footnote-rule">\n<ol class="footnotes">\n';
md.renderer.rules.footnote_block_close = () => "</ol>\n";

/* ---------- page chrome ---------- */

function nav(current) {
  const items = [["/", "home"], ["/reading/", "reading"], [`/${SITE.seg}/`, SITE.seg], ["/uni/", "uni"]];
  return items.map(([href, label]) =>
    `<a href="${href}"${label === current ? ' aria-current="page"' : ""}>${label}</a>`
  ).join("\n      ");
}

// the only visible way to subscribe: the autodiscovery <link> in <head> is
// invisible to a reader. It rides the writing pages alone, since they are the
// only ones the feed covers.
const feedLink = `<a href="/${SITE.seg}/feed.xml">rss</a>`;

function shell({ title, ogTitle, description, canonical, cwd, cmd, heading, meta, body,
                 current, needs, ogType = "article", sectionId = "post", src = "posts" }) {
  const head = [];
  if (needs?.katex) head.push('<link rel="stylesheet" href="/assets/katex/katex.min.css">');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${esc(canonical)}">
<meta property="og:type" content="${ogType}">
<meta property="og:title" content="${esc(ogTitle || title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${esc(canonical)}">
<meta property="og:site_name" content="${esc(SITE.author)}">
<meta name="twitter:card" content="summary">
<link rel="alternate" type="application/rss+xml" title="${esc(SITE.author)} — ${SITE.seg}" href="/${SITE.seg}/feed.xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,700;1,400&display=swap">
<link rel="stylesheet" href="/style.css">
${head.join("\n")}${head.length ? "\n" : ""}<script>
  // applied before first paint so a pinned theme doesn't flash the other one
  try {
    var saved = localStorage.getItem("theme");
    if (saved === "light" || saved === "dark") document.documentElement.dataset.theme = saved;
  } catch (e) {}
</script>
<script src="/theme.js" defer></script>
</head>
<body>
${MARKER(src)}
<div class="term">

<header>
  <p class="line line--top"><span><span class="ps1"><span class="user">${SITE.handle}</span>@<span class="host">web</span>:<span class="path">${esc(cwd)}</span>$</span> ${esc(cmd)}</span><button type="button" class="theme-toggle" id="theme-toggle" role="switch" aria-checked="true" aria-label="dark mode"><span class="track" aria-hidden="true"><span class="knob"></span></span></button></p>
  <div class="titlebar">
    <h1>${esc(SITE.author)}</h1>
    <nav class="nav">
      ${nav(current)}
    </nav>
  </div>
  ${meta}
</header>

<main>

  <section id="${sectionId}">
    <h2>${heading}</h2>
${body}
  </section>

</main>

<footer>
  <p class="line"><span class="ps1"><span class="user">${SITE.handle}</span>@<span class="host">web</span>:<span class="path">${esc(cwd)}</span>$</span> <span class="cursor"></span></p>
</footer>

</div>

</body>
</html>
`;
}

/* ---------- load posts ---------- */

function load(dir, isDraft) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith(".md")).map((file) => {
    const full = path.join(dir, file);
    const { meta, body } = frontMatter(fs.readFileSync(full, "utf8"), file);
    for (const key of ["title", "date", "description"]) {
      if (!meta[key]) throw new Error(`${file}: front matter needs a "${key}"`);
    }
    if (!/^\d{4}-\d{2}-\d{2}$/.test(meta.date)) {
      throw new Error(`${file}: date must be YYYY-MM-DD, got "${meta.date}"`);
    }
    const html = md.render(body);
    const words = html.replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
    return {
      slug: file.replace(/\.md$/, ""),
      title: meta.title,
      date: meta.date,
      updated: meta.updated || null,
      description: meta.description,
      html,
      isDraft,
      words,
      minutes: Math.max(1, Math.round(words / 200)),
      // the build knows what it actually rendered, so assets stay opt-in
      usesMath: html.includes('class="katex'),
    };
  });
}

const posts = [...load(path.join(ROOT, "posts"), false),
               ...(withDrafts ? load(path.join(ROOT, "drafts"), true) : [])]
  .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.slug < b.slug ? 1 : -1));

const seen = new Set();
for (const p of posts) {
  if (seen.has(p.slug)) throw new Error(`duplicate slug "${p.slug}"`);
  seen.add(p.slug);
}

/* ---------- write ---------- */

// writing/ is fully generated, so wipe it: a leftover directory from a
// deleted or draft post would otherwise linger in the published site
if (fs.existsSync(OUT)) {
  const stray = fs.readdirSync(OUT).find((f) => {
    const idx = path.join(OUT, f, "index.html");
    return fs.statSync(path.join(OUT, f)).isDirectory() &&
      !(fs.existsSync(idx) && fs.readFileSync(idx, "utf8").includes(GENERATED));
  });
  if (stray) throw new Error(`${SITE.seg}/${stray}/ was not generated by build.js — refusing to delete it`);
  fs.rmSync(OUT, { recursive: true });
}
fs.mkdirSync(OUT, { recursive: true });

const cwd = `~/${SITE.seg}`;

posts.forEach((post, i) => {
  const newer = posts[i - 1];
  const older = posts[i + 1];
  const links = older || newer ? `\n\n    <nav class="postnav">\n    ` + [
    older ? `<a class="older" href="/${SITE.seg}/${older.slug}/">← ${esc(older.title)}</a>` : "<span></span>",
    newer ? `<a class="newer" href="/${SITE.seg}/${newer.slug}/">${esc(newer.title)} →</a>` : "<span></span>",
  ].join("\n    ") + `\n    </nav>` : "";

  const stamp = [
    `<time datetime="${post.date}">${human(post.date)}</time>`,
    post.updated ? `updated ${human(post.updated)}` : null,
    `${post.minutes} min`,
    post.isDraft ? '<span class="draft-flag">draft</span>' : null,
    feedLink,
  ].filter(Boolean).join(" · ");

  fs.mkdirSync(path.join(OUT, post.slug), { recursive: true });
  fs.writeFileSync(path.join(OUT, post.slug, "index.html"), shell({
    title: `${post.title} — Ashmit Rao`,
    ogTitle: post.title,
    description: post.description,
    canonical: `${SITE.origin}/${SITE.seg}/${post.slug}/`,
    cwd,
    cmd: `cat ${post.slug}.md`,
    heading: esc(post.title),
    meta: `<p class="tagline post-meta">${stamp}</p>`,
    body: `    <div class="out prose">\n${post.html}    </div>${links}`,
    current: null,
    needs: { katex: post.usesMath },
  }));
});

// index, grouped by year
const byYear = new Map();
for (const p of posts) {
  const y = p.date.slice(0, 4);
  if (!byYear.has(y)) byYear.set(y, []);
  byYear.get(y).push(p);
}
const rows = posts.length
  ? [...byYear].map(([year, list]) => {
      const items = list.map((p) => `      <div class="row">
        <span class="date"><time datetime="${p.date}">${human(p.date)}</time></span>
        <span class="name"><a href="/${SITE.seg}/${p.slug}/">${esc(p.title)}</a></span>${p.isDraft ? '<span class="draft-flag">draft</span>' : ""}
        <p class="desc">${esc(p.description)}</p>
      </div>`).join("\n");
      return `      <p class="sub">${year}</p>\n${items}`;
    }).join("\n")
  : '      <p class="desc">nothing here yet.</p>';

fs.writeFileSync(path.join(OUT, "index.html"), shell({
  title: `${SITE.seg} — Ashmit Rao`,
  description: `Essays and notes by ${SITE.author}.`,
  canonical: `${SITE.origin}/${SITE.seg}/`,
  cwd,
  cmd: "ls -lt",
  heading: SITE.seg,
  meta: `<p class="tagline">thinking out loud. · ${feedLink}</p>`,
  body: `    <div class="out">\n${rows}\n    </div>`,
  current: SITE.seg,
  needs: {},
  ogType: "website",
  sectionId: SITE.seg,
}));

// feed — lastBuildDate is the newest post, not the clock, to keep builds stable
const live = posts.filter((p) => !p.isDraft);
const feedDate = live.length ? rfc822(live[0].date) : rfc822("1970-01-01");
fs.writeFileSync(path.join(OUT, "feed.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>${esc(SITE.author)} — ${SITE.seg}</title>
  <link>${SITE.origin}/${SITE.seg}/</link>
  <description>Essays and notes by ${esc(SITE.author)}.</description>
  <language>en</language>
  <lastBuildDate>${feedDate}</lastBuildDate>
  <atom:link href="${SITE.origin}/${SITE.seg}/feed.xml" rel="self" type="application/rss+xml"/>
${live.map((p) => `  <item>
    <title>${esc(p.title)}</title>
    <link>${SITE.origin}/${SITE.seg}/${p.slug}/</link>
    <guid isPermaLink="true">${SITE.origin}/${SITE.seg}/${p.slug}/</guid>
    <pubDate>${rfc822(p.date)}</pubDate>
    <description>${esc(p.description)}</description>
  </item>`).join("\n")}
</channel>
</rss>
`);

/* ---------- uni ---------- */

// the two orderings the section groups by. a year or term outside these fails
// the build rather than sorting somewhere arbitrary, and the "newest" open
// tier is read off the data, never off a clock.
const YEARS = ["prelims", "part a", "part b", "part c"];
const TERMS = ["michaelmas", "hilary", "trinity"];

const MODULES = path.join(ROOT, "modules");
const UNI = path.join(ROOT, "uni");
const uniCwd = "~/uni";

const hasMath = (html) => html.includes('class="katex');

// a module is a directory: module.md is required, notes.md and cards.txt are
// optional and their mere presence is what puts a link on the module page
function loadModules() {
  if (!fs.existsSync(MODULES)) return [];
  return fs.readdirSync(MODULES)
    .filter((d) => fs.statSync(path.join(MODULES, d)).isDirectory())
    .map((slug) => {
      const dir = path.join(MODULES, slug);
      const where = `modules/${slug}`;
      const src = path.join(dir, "module.md");
      if (!fs.existsSync(src)) throw new Error(`${where}/: no module.md`);

      const { meta, body } = frontMatter(fs.readFileSync(src, "utf8"), `${where}/module.md`);
      for (const key of ["title", "year", "term", "description"]) {
        if (!meta[key]) throw new Error(`${where}/module.md: front matter needs a "${key}"`);
      }
      const year = meta.year.toLowerCase();
      const term = meta.term.toLowerCase();
      if (!YEARS.includes(year)) {
        throw new Error(`${where}/module.md: year must be one of ${YEARS.join(", ")} — got "${meta.year}"`);
      }
      if (!TERMS.includes(term)) {
        throw new Error(`${where}/module.md: term must be one of ${TERMS.join(", ")} — got "${meta.term}"`);
      }
      if (meta.updated && !/^\d{4}-\d{2}-\d{2}$/.test(meta.updated)) {
        throw new Error(`${where}/module.md: updated must be YYYY-MM-DD, got "${meta.updated}"`);
      }

      const notesSrc = path.join(dir, "notes.md");
      const cardsSrc = path.join(dir, "cards.txt");
      const deck = fs.existsSync(cardsSrc)
        ? parseDeck(fs.readFileSync(cardsSrc, "utf8"), `${where}/cards.txt`)
        : null;

      const thoughts = md.render(body);
      const notes = fs.existsSync(notesSrc) ? md.render(fs.readFileSync(notesSrc, "utf8")) : null;
      const cards = deck ? deck.cards : null;

      return {
        slug, title: meta.title, year, term,
        description: meta.description,
        status: meta.status || null,
        lecturer: meta.lecturer || null,
        updated: meta.updated || null,
        thoughts, notes, cards,
        noMedia: deck ? deck.noMedia : [],
        thoughtsMath: hasMath(thoughts),
        notesMath: notes ? hasMath(notes) : false,
        cardsMath: cards ? cards.some((c) => hasMath(c.front + c.back)) : false,
      };
    })
    .sort((a, b) =>
      YEARS.indexOf(a.year) - YEARS.indexOf(b.year) ||
      TERMS.indexOf(a.term) - TERMS.indexOf(b.term) ||
      (a.title < b.title ? -1 : a.title > b.title ? 1 : 0));
}

const modules = loadModules();

const uniSeen = new Set();
for (const m of modules) {
  if (uniSeen.has(m.slug)) throw new Error(`duplicate module "${m.slug}"`);
  uniSeen.add(m.slug);
}

// same guard as writing/: refuse to delete a directory this script did not write
if (fs.existsSync(UNI)) {
  const stray = fs.readdirSync(UNI).find((f) => {
    const idx = path.join(UNI, f, "index.html");
    return fs.statSync(path.join(UNI, f)).isDirectory() &&
      !(fs.existsSync(idx) && fs.readFileSync(idx, "utf8").includes(GENERATED));
  });
  if (stray) throw new Error(`uni/${stray}/ was not generated by build.js — refusing to delete it`);
  fs.rmSync(UNI, { recursive: true });
}
fs.mkdirSync(UNI, { recursive: true });

const uniStamp = (m, extra = []) => [
  m.year, m.term,
  m.lecturer ? esc(m.lecturer) : null,
  m.status ? `<span class="flag">${esc(m.status)}</span>` : null,
  m.updated ? `updated ${human(m.updated)}` : null,
  ...extra,
].filter(Boolean).join(" · ");

modules.forEach((m) => {
  const dir = path.join(UNI, m.slug);
  fs.mkdirSync(dir, { recursive: true });

  const files = [
    m.notes ? `      <p class="item"><a href="/uni/${m.slug}/notes/">notes</a></p>` : null,
    m.cards ? `      <p class="item"><a href="/uni/${m.slug}/cards/">flashcards</a> <span class="count">${m.cards.length} card${m.cards.length === 1 ? "" : "s"}</span></p>` : null,
  ].filter(Boolean);

  fs.writeFileSync(path.join(dir, "index.html"), shell({
    title: `${m.title} — Ashmit Rao`,
    ogTitle: m.title,
    description: m.description,
    canonical: `${SITE.origin}/uni/${m.slug}/`,
    cwd: `${uniCwd}/${m.slug}`,
    cmd: "cat module.md",
    heading: esc(m.title),
    meta: `<p class="tagline post-meta">${uniStamp(m)}</p>`,
    body: `    <div class="out prose">\n${m.thoughts}    </div>` +
      (files.length ? `\n\n    <div class="out files">\n${files.join("\n")}\n    </div>` : ""),
    current: null,
    needs: { katex: m.thoughtsMath },
    sectionId: "module",
    src: "modules",
  }));

  if (m.notes) {
    fs.mkdirSync(path.join(dir, "notes"), { recursive: true });
    fs.writeFileSync(path.join(dir, "notes", "index.html"), shell({
      title: `${m.title} notes — Ashmit Rao`,
      ogTitle: `${m.title} — notes`,
      description: `Notes on ${m.title}.`,
      canonical: `${SITE.origin}/uni/${m.slug}/notes/`,
      cwd: `${uniCwd}/${m.slug}`,
      cmd: "cat notes.md",
      heading: "notes",
      meta: `<p class="tagline post-meta"><a href="/uni/${m.slug}/">${esc(m.title)}</a> · ${uniStamp(m)}</p>`,
      body: `    <div class="out prose">\n${m.notes}    </div>`,
      current: null,
      needs: { katex: m.notesMath },
      sectionId: "notes",
      src: "modules",
    }));
  }

  if (m.cards) {
    fs.mkdirSync(path.join(dir, "cards"), { recursive: true });
    // <details> is the whole mechanism: a card flips with no javascript, and
    // the answer is still in the html for anyone reading without it
    const deck = m.cards.length
      ? m.cards.map((c) => `      <details class="card">
        <summary><span class="q">${c.front}</span></summary>
        <div class="a">${c.back || "&mdash;"}</div>
      </details>`).join("\n")
      : '      <p class="desc">this deck is empty.</p>';

    fs.writeFileSync(path.join(dir, "cards", "index.html"), shell({
      title: `${m.title} flashcards — Ashmit Rao`,
      ogTitle: `${m.title} — flashcards`,
      description: `Flashcards for ${m.title}.`,
      canonical: `${SITE.origin}/uni/${m.slug}/cards/`,
      cwd: `${uniCwd}/${m.slug}`,
      cmd: "cat cards.txt",
      heading: "flashcards",
      meta: `<p class="tagline post-meta"><a href="/uni/${m.slug}/">${esc(m.title)}</a> · ${m.cards.length} card${m.cards.length === 1 ? "" : "s"} · click to flip</p>`,
      body: `    <div class="out cards">\n${deck}\n    </div>`,
      current: null,
      needs: { katex: m.cardsMath },
      sectionId: "cards",
      src: "modules",
    }));
  }
});

// index — year > term > module, nested <details> so it expands with no script
const uniBody = (() => {
  if (!modules.length) return '      <p class="desc">nothing here yet.</p>';
  const years = YEARS.filter((y) => modules.some((m) => m.year === y));
  const openYear = years[years.length - 1];
  return years.map((year) => {
    const inYear = modules.filter((m) => m.year === year);
    const terms = TERMS.filter((t) => inYear.some((m) => m.term === t));
    const openTerm = terms[terms.length - 1];
    const body = terms.map((term) => {
      const rows = inYear.filter((m) => m.term === term).map((m) => `          <div class="row">
            <span class="name"><a href="/uni/${m.slug}/">${esc(m.title)}</a></span>${m.status ? `<span class="flag">${esc(m.status)}</span>` : ""}
            <p class="desc">${esc(m.description)}</p>
          </div>`).join("\n");
      return `        <details class="tier tier--term"${year === openYear && term === openTerm ? " open" : ""}>
          <summary>${term}</summary>
${rows}
        </details>`;
    }).join("\n");
    return `      <details class="tier tier--year"${year === openYear ? " open" : ""}>
        <summary>${year}</summary>
${body}
      </details>`;
  }).join("\n");
})();

fs.writeFileSync(path.join(UNI, "index.html"), shell({
  title: "uni — Ashmit Rao",
  description: `Modules ${SITE.author} has taken at Oxford, with notes and flashcards.`,
  canonical: `${SITE.origin}/uni/`,
  cwd: uniCwd,
  cmd: "tree",
  heading: "uni",
  meta: `<p class="tagline">what i'm studying!</p>`,
  body: `    <div class="out">\n${uniBody}\n    </div>`,
  current: "uni",
  needs: {},
  ogType: "website",
  sectionId: "uni",
  src: "modules",
}));

// sitemap
const urls = [
  { loc: `${SITE.origin}/`, mod: null },
  { loc: `${SITE.origin}/reading/`, mod: null },
  { loc: `${SITE.origin}/${SITE.seg}/`, mod: live.length ? live[0].date : null },
  ...live.map((p) => ({ loc: `${SITE.origin}/${SITE.seg}/${p.slug}/`, mod: p.updated || p.date })),
  { loc: `${SITE.origin}/uni/`, mod: null },
  ...modules.flatMap((m) => [
    { loc: `${SITE.origin}/uni/${m.slug}/`, mod: m.updated },
    ...(m.notes ? [{ loc: `${SITE.origin}/uni/${m.slug}/notes/`, mod: m.updated }] : []),
    ...(m.cards ? [{ loc: `${SITE.origin}/uni/${m.slug}/cards/`, mod: m.updated }] : []),
  ]),
];
fs.writeFileSync(path.join(ROOT, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u.loc}</loc>${u.mod ? `<lastmod>${u.mod}</lastmod>` : ""}</url>`).join("\n")}
</urlset>
`);

/* ---------- katex assets, only if something needs them ---------- */

const assets = path.join(ROOT, "assets", "katex");
const needsKatex = posts.some((p) => p.usesMath) ||
  modules.some((m) => m.thoughtsMath || m.notesMath || m.cardsMath);
if (needsKatex) {
  const dist = path.join(ROOT, "node_modules", "katex", "dist");
  fs.mkdirSync(path.join(assets, "fonts"), { recursive: true });
  fs.copyFileSync(path.join(dist, "katex.min.css"), path.join(assets, "katex.min.css"));
  for (const f of fs.readdirSync(path.join(dist, "fonts")).filter((f) => f.endsWith(".woff2"))) {
    fs.copyFileSync(path.join(dist, "fonts", f), path.join(assets, "fonts", f));
  }
} else if (fs.existsSync(assets)) {
  fs.rmSync(assets, { recursive: true });
}

/* ---------- report ---------- */

console.log(`built ${posts.length} post${posts.length === 1 ? "" : "s"} → /${SITE.seg}/`);
for (const p of posts) {
  const tags = [p.usesMath ? "maths" : null, p.isDraft ? "DRAFT" : null].filter(Boolean);
  console.log(`  ${p.date}  ${p.slug}${tags.length ? `  [${tags.join(", ")}]` : ""}`);
}
console.log(`built ${modules.length} module${modules.length === 1 ? "" : "s"} \u2192 /uni/`);
for (const m of modules) {
  const tags = [
    m.notes ? "notes" : null,
    m.cards ? `cards: ${m.cards.length}` : null,
    m.thoughtsMath || m.notesMath || m.cardsMath ? "maths" : null,
  ].filter(Boolean);
  console.log(`  ${m.year}/${m.term}  ${m.slug}${tags.length ? `  [${tags.join(", ")}]` : ""}`);
}

// a plain-text export carries no media, so these cards would publish blank
const orphaned = modules.flatMap((m) => m.noMedia);
if (orphaned.length) {
  console.log(`\n  ! ${orphaned.length} card(s) reference an image the export did not include:`);
  for (const o of orphaned) console.log(`      ${o}`);
}

console.log(`katex assets: ${needsKatex ? "linked where needed" : "not needed, omitted"}`);
if (withDrafts) {
  console.log("\n  ! drafts are in the output tree — run `node build.js` before committing");
}
