// build.js — renders posts/*.md into /writing/.
//
// maths and syntax highlighting are resolved here rather than in the browser,
// so a published post carries no javascript and never flashes raw "$x^2$".
// a post that uses neither also links neither stylesheet.
//
//   node build.js            build posts/ into writing/
//   node build.js --drafts   also build drafts/, for local preview only
//
// the output is a pure function of the sources: writing/ is wiped and
// regenerated each run, which is what lets ci detect a stale commit.

import fs from "node:fs";
import path from "node:path";
import MarkdownIt from "markdown-it";
import anchor from "markdown-it-anchor";
import footnote from "markdown-it-footnote";
import container from "markdown-it-container";
import katexPlugin from "@vscode/markdown-it-katex";
import { createHighlighter } from "shiki";

const SITE = {
  origin: "https://ashmitrao.com",
  author: "Ashmit Rao",
  handle: "ashmit",
  seg: "writing", // url segment, nav label and shell path all at once
};

const ROOT = import.meta.dirname;
const OUT = path.join(ROOT, SITE.seg);
const MARKER = "<!-- generated by build.js — edit the markdown in posts/, not this file -->";

const withDrafts = process.argv.includes("--drafts");

/* ---------- helpers ---------- */

const esc = (s) =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const MONTHS = ["jan","feb","mar","apr","may","jun","jul","aug","sep","oct","nov","dec"];
// dates are formatted from the iso string, never from a clock, so that a
// rebuild on a different day produces byte-identical output
function human(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  return `${d} ${MONTHS[m - 1]} ${y}`;
}
function rfc822(iso) {
  return new Date(`${iso}T12:00:00Z`).toUTCString();
}

// a deliberately small front-matter subset: "key: value" lines, no nesting
function frontMatter(raw, file) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) throw new Error(`${file}: missing --- front matter block`);
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    if (!line.trim()) continue;
    const at = line.indexOf(":");
    if (at === -1) throw new Error(`${file}: bad front-matter line "${line}"`);
    meta[line.slice(0, at).trim()] = line.slice(at + 1).trim();
  }
  return { meta, body: raw.slice(m[0].length) };
}

/* ---------- markdown ---------- */

const THEOREMS = ["theorem", "lemma", "definition", "proof", "remark"];

const highlighter = await createHighlighter({
  themes: ["vitesse-light", "vitesse-dark"],
  langs: ["lean4", "python", "haskell", "rust", "bash", "javascript", "typescript",
          "json", "html", "css", "sql", "c", "cpp", "latex", "diff", "text"],
});

const md = new MarkdownIt({
  html: true,      // an escape hatch for the odd bit of raw markup
  linkify: true,
  typographer: false, // straight quotes suit a monospace page
  highlight(code, lang) {
    const known = highlighter.getLoadedLanguages().includes(lang);
    // defaultColor:false emits both palettes as css variables, so the theme
    // toggle drives code colour from style.css with no javascript
    return highlighter.codeToHtml(code.replace(/\n$/, ""), {
      lang: known ? lang : "text",
      themes: { light: "vitesse-light", dark: "vitesse-dark" },
      defaultColor: false,
    });
  },
});

md.use(footnote);
md.use(katexPlugin.default ?? katexPlugin);
md.use(anchor, {
  level: [2, 3, 4],
  permalink: anchor.permalink.linkInsideHeader({
    symbol: "#", placement: "after", class: "anchor", ariaHidden: true,
  }),
});
for (const kind of THEOREMS) {
  md.use(container, kind, {
    render(tokens, i) {
      if (tokens[i].nesting !== 1) return "</div>\n";
      const name = tokens[i].info.trim().slice(kind.length).trim();
      const label = name ? `${kind} — ${name}` : kind;
      return `<div class="thm thm--${kind}"><p class="thm-label">${esc(label)}</p>\n`;
    },
  });
}

// the post title already occupies <h2>, so "## foo" in a post becomes <h3>
md.core.ruler.push("demote_headings", (state) => {
  for (const t of state.tokens) {
    if (t.type === "heading_open" || t.type === "heading_close") {
      t.tag = "h" + Math.min(Number(t.tag.slice(1)) + 1, 6);
    }
  }
});

// footnote headings would duplicate the post's own <h2>; drop the rule/label
md.renderer.rules.footnote_block_open = () =>
  '<hr class="footnote-rule">\n<ol class="footnotes">\n';
md.renderer.rules.footnote_block_close = () => "</ol>\n";

/* ---------- page chrome ---------- */

function nav(current) {
  const items = [["/", "home"], ["/reading/", "reading"], [`/${SITE.seg}/`, SITE.seg]];
  return items.map(([href, label]) =>
    `<a href="${href}"${label === current ? ' aria-current="page"' : ""}>${label}</a>`
  ).join("\n      ");
}

function shell({ title, ogTitle, description, canonical, cwd, cmd, heading, meta, body, current, needs }) {
  const head = [];
  if (needs?.katex) head.push('<link rel="stylesheet" href="/assets/katex/katex.min.css">');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${esc(canonical)}">
<meta property="og:type" content="${current === SITE.seg ? "website" : "article"}">
<meta property="og:title" content="${esc(ogTitle || title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:url" content="${esc(canonical)}">
<meta property="og:site_name" content="${esc(SITE.author)}">
<meta name="twitter:card" content="summary">
<link rel="alternate" type="application/rss+xml" title="${esc(SITE.author)} — ${SITE.seg}" href="/${SITE.seg}/feed.xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,700;1,400&display=swap">
<link rel="stylesheet" href="/style.css">
${head.join("\n")}${head.length ? "\n" : ""}<script>
  // applied before first paint so a pinned theme doesn't flash the other one
  try {
    var saved = localStorage.getItem("theme");
    if (saved === "light" || saved === "dark") document.documentElement.dataset.theme = saved;
  } catch (e) {}
</script>
<script src="/theme.js" defer></script>
</head>
<body>
${MARKER}
<div class="term">

<header>
  <p class="line line--top"><span><span class="ps1"><span class="user">${SITE.handle}</span>@<span class="host">web</span>:<span class="path">${esc(cwd)}</span>$</span> ${esc(cmd)}</span><button type="button" class="theme-toggle" id="theme-toggle" role="switch" aria-checked="true" aria-label="dark mode"><span class="track" aria-hidden="true"><span class="knob"></span></span></button></p>
  <div class="titlebar">
    <h1>${esc(SITE.author)}</h1>
    <nav class="nav">
      ${nav(current)}
    </nav>
  </div>
  ${meta}
</header>

<main>

  <section id="${current === SITE.seg ? SITE.seg : "post"}">
    <h2>${heading}</h2>
${body}
  </section>

</main>

<footer>
  <p class="line"><span class="ps1"><span class="user">${SITE.handle}</span>@<span class="host">web</span>:<span class="path">${esc(cwd)}</span>$</span> <span class="cursor"></span></p>
</footer>

</div>

</body>
</html>
`;
}

/* ---------- load posts ---------- */

function load(dir, isDraft) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith(".md")).map((file) => {
    const full = path.join(dir, file);
    const { meta, body } = frontMatter(fs.readFileSync(full, "utf8"), file);
    for (const key of ["title", "date", "description"]) {
      if (!meta[key]) throw new Error(`${file}: front matter needs a "${key}"`);
    }
    if (!/^\d{4}-\d{2}-\d{2}$/.test(meta.date)) {
      throw new Error(`${file}: date must be YYYY-MM-DD, got "${meta.date}"`);
    }
    const html = md.render(body);
    const words = html.replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
    return {
      slug: file.replace(/\.md$/, ""),
      title: meta.title,
      date: meta.date,
      updated: meta.updated || null,
      description: meta.description,
      html,
      isDraft,
      words,
      minutes: Math.max(1, Math.round(words / 200)),
      // the build knows what it actually rendered, so assets stay opt-in
      usesMath: html.includes('class="katex'),
    };
  });
}

const posts = [...load(path.join(ROOT, "posts"), false),
               ...(withDrafts ? load(path.join(ROOT, "drafts"), true) : [])]
  .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.slug < b.slug ? 1 : -1));

const seen = new Set();
for (const p of posts) {
  if (seen.has(p.slug)) throw new Error(`duplicate slug "${p.slug}"`);
  seen.add(p.slug);
}

/* ---------- write ---------- */

// writing/ is fully generated, so wipe it: a leftover directory from a
// deleted or draft post would otherwise linger in the published site
if (fs.existsSync(OUT)) {
  const stray = fs.readdirSync(OUT).find((f) => {
    const idx = path.join(OUT, f, "index.html");
    return fs.statSync(path.join(OUT, f)).isDirectory() &&
      !(fs.existsSync(idx) && fs.readFileSync(idx, "utf8").includes(MARKER));
  });
  if (stray) throw new Error(`${SITE.seg}/${stray}/ was not generated by build.js — refusing to delete it`);
  fs.rmSync(OUT, { recursive: true });
}
fs.mkdirSync(OUT, { recursive: true });

const cwd = `~/${SITE.seg}`;

posts.forEach((post, i) => {
  const newer = posts[i - 1];
  const older = posts[i + 1];
  const links = older || newer ? `\n\n    <nav class="postnav">\n    ` + [
    older ? `<a class="older" href="/${SITE.seg}/${older.slug}/">← ${esc(older.title)}</a>` : "<span></span>",
    newer ? `<a class="newer" href="/${SITE.seg}/${newer.slug}/">${esc(newer.title)} →</a>` : "<span></span>",
  ].join("\n    ") + `\n    </nav>` : "";

  const stamp = [
    `<time datetime="${post.date}">${human(post.date)}</time>`,
    post.updated ? `updated ${human(post.updated)}` : null,
    `${post.minutes} min`,
    post.isDraft ? '<span class="draft-flag">draft</span>' : null,
  ].filter(Boolean).join(" · ");

  fs.mkdirSync(path.join(OUT, post.slug), { recursive: true });
  fs.writeFileSync(path.join(OUT, post.slug, "index.html"), shell({
    title: `${post.title} — Ashmit Rao`,
    ogTitle: post.title,
    description: post.description,
    canonical: `${SITE.origin}/${SITE.seg}/${post.slug}/`,
    cwd,
    cmd: `cat ${post.slug}.md`,
    heading: esc(post.title),
    meta: `<p class="tagline post-meta">${stamp}</p>`,
    body: `    <div class="out prose">\n${post.html}    </div>${links}`,
    current: null,
    needs: { katex: post.usesMath },
  }));
});

// index, grouped by year
const byYear = new Map();
for (const p of posts) {
  const y = p.date.slice(0, 4);
  if (!byYear.has(y)) byYear.set(y, []);
  byYear.get(y).push(p);
}
const rows = posts.length
  ? [...byYear].map(([year, list]) => {
      const items = list.map((p) => `      <div class="row">
        <span class="date"><time datetime="${p.date}">${human(p.date)}</time></span>
        <span class="name"><a href="/${SITE.seg}/${p.slug}/">${esc(p.title)}</a></span>${p.isDraft ? '<span class="draft-flag">draft</span>' : ""}
        <p class="desc">${esc(p.description)}</p>
      </div>`).join("\n");
      return `      <p class="sub">${year}</p>\n${items}`;
    }).join("\n")
  : '      <p class="desc">nothing here yet.</p>';

fs.writeFileSync(path.join(OUT, "index.html"), shell({
  title: `${SITE.seg} — Ashmit Rao`,
  description: `Essays and notes by ${SITE.author}.`,
  canonical: `${SITE.origin}/${SITE.seg}/`,
  cwd,
  cmd: "ls -lt",
  heading: SITE.seg,
  meta: '<p class="tagline">thinking out loud.</p>',
  body: `    <div class="out">\n${rows}\n    </div>`,
  current: SITE.seg,
  needs: {},
}));

// feed — lastBuildDate is the newest post, not the clock, to keep builds stable
const live = posts.filter((p) => !p.isDraft);
const feedDate = live.length ? rfc822(live[0].date) : rfc822("1970-01-01");
fs.writeFileSync(path.join(OUT, "feed.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <title>${esc(SITE.author)} — ${SITE.seg}</title>
  <link>${SITE.origin}/${SITE.seg}/</link>
  <description>Essays and notes by ${esc(SITE.author)}.</description>
  <language>en</language>
  <lastBuildDate>${feedDate}</lastBuildDate>
  <atom:link href="${SITE.origin}/${SITE.seg}/feed.xml" rel="self" type="application/rss+xml"/>
${live.map((p) => `  <item>
    <title>${esc(p.title)}</title>
    <link>${SITE.origin}/${SITE.seg}/${p.slug}/</link>
    <guid isPermaLink="true">${SITE.origin}/${SITE.seg}/${p.slug}/</guid>
    <pubDate>${rfc822(p.date)}</pubDate>
    <description>${esc(p.description)}</description>
  </item>`).join("\n")}
</channel>
</rss>
`);

// sitemap
const urls = [
  { loc: `${SITE.origin}/`, mod: null },
  { loc: `${SITE.origin}/reading/`, mod: null },
  { loc: `${SITE.origin}/${SITE.seg}/`, mod: live.length ? live[0].date : null },
  ...live.map((p) => ({ loc: `${SITE.origin}/${SITE.seg}/${p.slug}/`, mod: p.updated || p.date })),
];
fs.writeFileSync(path.join(ROOT, "sitemap.xml"), `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u.loc}</loc>${u.mod ? `<lastmod>${u.mod}</lastmod>` : ""}</url>`).join("\n")}
</urlset>
`);

/* ---------- katex assets, only if something needs them ---------- */

const assets = path.join(ROOT, "assets", "katex");
const needsKatex = posts.some((p) => p.usesMath);
if (needsKatex) {
  const dist = path.join(ROOT, "node_modules", "katex", "dist");
  fs.mkdirSync(path.join(assets, "fonts"), { recursive: true });
  fs.copyFileSync(path.join(dist, "katex.min.css"), path.join(assets, "katex.min.css"));
  for (const f of fs.readdirSync(path.join(dist, "fonts")).filter((f) => f.endsWith(".woff2"))) {
    fs.copyFileSync(path.join(dist, "fonts", f), path.join(assets, "fonts", f));
  }
} else if (fs.existsSync(assets)) {
  fs.rmSync(assets, { recursive: true });
}

/* ---------- report ---------- */

const mathCount = posts.filter((p) => p.usesMath).length;
console.log(`built ${posts.length} post${posts.length === 1 ? "" : "s"} → /${SITE.seg}/`);
for (const p of posts) {
  const tags = [p.usesMath ? "maths" : null, p.isDraft ? "DRAFT" : null].filter(Boolean);
  console.log(`  ${p.date}  ${p.slug}${tags.length ? `  [${tags.join(", ")}]` : ""}`);
}
console.log(`katex assets: ${needsKatex ? `linked from ${mathCount} post(s)` : "not needed, omitted"}`);
if (withDrafts) {
  console.log("\n  ! drafts are in the output tree — run `node build.js` before committing");
}
